### ISSUE TITLE
Consider using Github Actions for release

### ISSUE THREAD

**Issue by ffoodd** [mcguffin/acf-field-openstreetmap#10]
Thanks to @10up, there's a [Github Action to deploy release to WordPress plugins repository](https://github.com/10up/actions-wordpress). They also [wrote a post to introduce their Github Action](https://10up.com/blog/2019/introducing-github-actions-for-wordpress-plugins/).

It could allow you to publish your plugin on the official repository while keeping your work on Github — and therefore to remove all the Github updater part all along.

It's up to you but I thought you could be interested :)

**Comment by mcguffin** [comment]
Thanks! This looks like the thing I've always been waiting for. I'll give it try!
.. if the beta confirmation arrives eventually :)

**Comment by mcguffin** [comment]
It's been over three months I applied for the github actions beta, but no response yet…
So I decided to write my own node-based deploy-to-wp.org-o-matic. (Already tested with [this deprecation candidate](https://github.com/mcguffin/wp-rainbow-hilite))

**Comment by mcguffin** [comment]
The plugin is at wporg now: https://wordpress.org/plugins/acf-openstreetmap-field/

**Comment by ffoodd** [comment]
Awesome, thank you!
