### ISSUE TITLE
1.5.3 | Uncaught ReferenceError: marker is not defined

### ISSUE THREAD

**Issue by MaxRenglet** [mcguffin/acf-field-openstreetmap#105]
Hi,

Just to let you know that the plugin seem to have an error when searching for an address :

![Capture d'écran 2023-11-07 153251](https://github.com/mcguffin/acf-openstreetmap-field/assets/5802651/77407fc8-9884-4dad-b893-9b6be41a810f)

I don't have the time to dig in the plugin..

**Comment by MaxRenglet** [comment]
@mcguffin Thanks !

**Comment by bastien-martinent** [comment]
Hi,
there is a another bug here, i have a case where a have 1 max map marker
no mapmarker already set and L503 to L505 is executed and crash.
i have no idee why canAddMarker do not return true in this case.
if a map marker is set everythink work fine.

`map-input.js:504 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at t.<anonymous> (map-input.js:504:30)
    at t.fire (leaflet-src.js:606:1)
    at e._geocodeResultSelected (Control.Geocoder.js:1774:1)
    at t.<anonymous> (Control.Geocoder.js:1830:1)
    at HTMLLIElement.n (leaflet-src.js:2799:1)`
