### ISSUE TITLE
map-input.js:504 Uncaught TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by bastien-martinent** [mcguffin/acf-field-openstreetmap#108]
Hi,
I found a bug when you use 1 has a marker limit, the map have no marker and you try a search.
i cant figure out why this.canAddmarker do not send a true and execute this code...
but it cant find any marker and crash.

![image](https://github.com/mcguffin/acf-openstreetmap-field/assets/55284484/dd516e2a-0fb2-49ae-9727-4765dd457ec7)

map-input.js:504 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at t.<anonymous> (map-input.js:504:30)
    at t.fire (leaflet-src.js:606:1)
    at e._geocodeResultSelected (Control.Geocoder.js:1774:1)
    at t.<anonymous> (Control.Geocoder.js:1830:1)
    at HTMLLIElement.n (leaflet-src.js:2799:1)

**Comment by margarita-boomCodes** [comment]
I would like to report something similar, when the OSM field is attached to a taxonomy and there are no markers defined yet. For example, when you add a new taxonomy term:

When I click on a result after I hitting enter, I get the same error as above in the console log. The same thing happens, when I do a search, but there are no results and no "Nothing found" message.

**Comment by margarita-boomCodes** [comment]
@mcguffin I would like to report, that with the 1.5.6 Version the bug is fixed :)
