### ISSUE TITLE
Marker dont return precise position (coordinates)

### ISSUE THREAD

**Issue by jorge-teixeira** [mcguffin/acf-field-openstreetmap#117]
When I place a marker in the custom post, the raw data  it is not saved with the precise location meaning it doesn’t go to the exact coordinates where the marker was placed. Instead, it always defaults to the nearest road. 
example: marker at:    40.1234567, -8.1234567 .

I try to use de Raw Data :
i put in the wordpress ACF map the coordenate 40.1234567, -8.1234567 and the output with the var_dump is :  array(9) { ["lat"]=> float(40.1235615) ["lng"]=> float(-8.1236286).

**Comment by mcguffin** [comment]
@jorge-teixeira Can you provide a step by step, what exactly you were doing?
I tried to manually set your coordinates for the marker, but they exactly appeared as entered.
