### ISSUE TITLE
Missing release publication ?

### ISSUE THREAD

**Issue by Cyrille37** [mcguffin/acf-field-openstreetmap#118]
Hi

At first a big thanks for this really great and useful plugin :-)

Commits talk about [Release 1.5.6](https://github.com/mcguffin/acf-openstreetmap-field/commit/17369601a16ea95735fba1ae553bb096e6b63e08) but [Releases page](https://github.com/mcguffin/acf-openstreetmap-field/releases) stay on 1.2.2

Thanks & cheers

**Comment by mcguffin** [comment]
Hi @Cyrille37 
since the plugin is on wporg too I skipped the github releases.
I see no reason to not bring them back, so stay tuned for 1.5.7...

**Comment by Cyrille37** [comment]
Thanks for pulbishing the 1.5.7 on github :-)

wporg doesn't make it easy to keep track of changes ;-)
