### ISSUE TITLE
Issue with unwanted warnings undefined variable

### ISSUE THREAD

**Issue by tnchuntic** [mcguffin/acf-field-openstreetmap#12]
Hi McGuffin just reporting this undefined variable warnings.

This occurs on both openstreetmap and duplicate repeater plugin.

Kind see image screenshot https://snag.gy/cz7LY8.jpg

Thanks

**Comment by mcguffin** [comment]
Hi, the plugin is available at wporg now: https://wordpress.org/plugins/acf-openstreetmap-field/
