### ISSUE TITLE
Mouse scroll zoom In and Out option

### ISSUE THREAD

**Issue by Raito00** [mcguffin/acf-field-openstreetmap#123]
Hi,
Really nice plugin to add maps but how to enable mouse scroll zoom IN and Out option?

**Comment by mcguffin** [comment]
These ones should give you a hint:
https://github.com/mcguffin/acf-openstreetmap-field/wiki/JS-Events#acf-osm-map-create
https://leafletjs.com/reference.html#map-scrollwheelzoom

**Comment by Raito00** [comment]
Thanks!
Your hint helped.

Fixed!
