### ISSUE TITLE
ERROR on /acf-openstreetmap-field/include/ACFFieldOpenstreetmap/Core/Plugin.php:131

### ISSUE THREAD

**Issue by StarAle** [mcguffin/acf-field-openstreetmap#126]
Hello,

I've just update to 1.6.0 and... WordPress site is gone! :-D
This is what I found in WP recovery mode:

`Un errore di E_ERROR è stato causato nella linea 131 del file /home/customer/www/magytour.com/public_html/wp-content/plugins/acf-openstreetmap-field/include/ACFFieldOpenstreetmap/Core/Plugin.php. Messaggio di errore: Uncaught Error: Call to undefined method ACFFieldOpenstreetmap\Core\Core::upgrade() in /home/customer/www/magytour.com/public_html/wp-content/plugins/acf-openstreetmap-field/include/ACFFieldOpenstreetmap/Core/Plugin.php:131 Stack trace: #0 /home/customer/www/magytour.com/public_html/wp-includes/class-wp-hook.php(324): ACFFieldOpenstreetmap\Core\Plugin->maybe_upgrade('') #1 /home/customer/www/magytour.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #2 /home/customer/www/magytour.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /home/customer/www/magytour.com/public_html/wp-admin/admin.php(175): do_action('admin_init') #4 /home/customer/www/magytour.com/public_html/wp-admin/plugins.php(10): require_once('/home/customer/...') #5 {main} thrown`

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.3.9
		Author: WP Engine

	Classic Editor
		Version: 1.6.7
		Author: WordPress Contributors

	Connect Polylang for Elementor
		Version: 2.4.5
		Author: Creame

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 3.2.1
		Author: Dynamic.ooo

	Elementor
		Version: 3.26.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.26.1
		Author: Elementor.com

	Polylang Pro
		Version: 3.6.4
		Author: WP SYNTEX

	Rank Math SEO
		Version: 1.0.234.1
		Author: Rank Math SEO

	Security Optimizer
		Version: 1.5.7
		Author: SiteGround

	SiteGround Central
		Version: 3.3.1
		Author: SiteGround

	Speed Optimizer
		Version: 7.7.2
		Author: SiteGround

	SVG Support
		Version: 2.5.8
		Author: Benbodhi

Thanks :-)

**Comment by interpixels** [comment]
I can confirm the white screen. The frontend seems to be functioning, but the WP dashboard is not accessible anymore after the update. I use the Bricks theme. Removing the plugin via FTP brings the dashboard back.

**Comment by realrellek** [comment]
Here's a hotfix for the meantime: https://wordpress.org/support/topic/version-1-6-0-breaks-wp-admin/
