### ISSUE TITLE
[wiki] corrects link "JS Events"

### ISSUE THREAD

**Issue by Cyrille37** [mcguffin/acf-field-openstreetmap#127]
Hi

At the end of page [Usage](https://github.com/mcguffin/acf-openstreetmap-field/wiki/Usage)  the link in "the JS-Events described on the [Reference Page](https://github.com/mcguffin/acf-openstreetmap-field/wiki/Reference)." should be link to "JS-Events" not "Reference" which does not exists ;-)

Regards & cheers

**Comment by mcguffin** [comment]
Thanks! The link is fixed. 

Happy hollidays!
