### ISSUE TITLE
[dev] how to run php test ?

### ISSUE THREAD

**Issue by Cyrille37** [mcguffin/acf-field-openstreetmap#130]
Hi,

I can see `test/test.php` but I do not find howto run test ...

It doesn't matter, I can do without it :-) If there is a solution, I can add tests to my PR.

**Comment by mcguffin** [comment]
Just run `npm run dev-test`, which is adding some maps and content to the backend for manual testing.
However, I'm currently working on proper PHP Unit Tests.
