### ISSUE TITLE
Can't add Marker on phone 

### ISSUE THREAD

**Issue by adamwolny** [mcguffin/acf-field-openstreetmap#18]
Hi, i can't add marker on my phone ,no matter if it's Android or iOS
Please reply as soon as possible

**Comment by mcguffin** [comment]
Adding markers on phone now via tap+hold. Works for me on Android and iOS Safari+Chrome. Firefox for iOS however is suffering from [this bug](https://github.com/Leaflet/Leaflet/issues/6860) in the leaflet lib, which might make adding markers a little painful...
