### ISSUE TITLE
Raw Data

### ISSUE THREAD

**Issue by benbelek** [mcguffin/acf-field-openstreetmap#19]
Hey !

This extension seems to be a very good alternative to google maps, thanks! 
I would like to use the raw data but i don't understant how can i can "echo" this in .php using leaflet API, in order to personalize the map !

Thanks

ben

**Comment by mcguffin** [comment]
Hi,
using raw data you are free to choose any map library you like in the frontend. It doesn't have to be leaflet, can be mapbox or something else.

In PHP `get_field()` returns an array holding the map data the user entered. 
Turning this into a map-ish representation in HTML, JS, SVG or anything else in any tool you choose is solely up to you. 
Heres some fresh documentation of the raw data return value: https://github.com/mcguffin/acf-openstreetmap-field/wiki/Usage#raw-data
If you want to work with leaflet, there are also some Links to get you started.

Regards,
jörn
