### ISSUE TITLE
Postcodes for Berlin

### ISSUE THREAD

**Issue by spa49** [mcguffin/acf-field-openstreetmap#26]
When I type in an address and search for it, I found that the postcodes for Berlin will not be displayed in the results list and subsequently in the marker field underneath the map.
However, other cities in Germany have the postcodes displayed in the results list as well as the marker field underneath.

So here my question:
what service actually delivers the postcode, is it OSM or a Leaflet provider?

**Comment by mcguffin** [comment]
Hi, geocoding (address to coordinate) is performed by [perliedman/leaflet-control-geocoder](https://github.com/perliedman/leaflet-control-geocoder) using the [default service](https://nominatim.org/release-docs/develop/api/Overview/).
