### ISSUE TITLE
Option to output map as static (for printig etc)

### ISSUE THREAD

**Issue by spa49** [mcguffin/acf-field-openstreetmap#31]
Hi again,

when trying to render a PDF on server side, the map field does not get shown. I suspect that is because the map is called dynamically.
I think it would be nice to have the option to render map via the static API as PNG f.e. for such applications. So instead of building a DIV it just passes an image url to the shortcode
Maybe it can be handled with a shortcode parameter like render-output = "static" so the settings for output can be overwritten.

what do you think?

**Comment by mcguffin** [comment]
Hmm. Using raw data return format you should be able to render the map through [OSM static Maps](https://staticmap.openstreetmap.de/), or [tyler](https://github.com/benbacardi/tyler).

However, both services look a bit neglected to me ... I wouldn't rely on them on a production system.

I'll consider adding a static map template when I start working on the Template Overrides (#25) … and if I find a reliable static map service.

**Comment by spa49** [comment]
Ja that sounds reasonable.
Well I will have a look at the render on runtime option with RAW and Mapbox API
Maybe for even caching/saving the static to disk or database until the map field has been altered.
I think [Mapboxs](https://docs.mapbox.com/api/maps/#static-images)
would also work if it needs to be rendered to print on runtime (like for frequently changing map info that needs printing or offline availability.
Also, they offer a leaflet plugin called [leaflet-image](https://github.com/mapbox/leaflet-image)
or how about just shooting an image of the maps DIV with [html2canvas](https://html2canvas.hertzen.com/)

**Comment by mcguffin** [comment]
&lt;basic&gt;goto #25&lt;/basic&gt; ;)
