### ISSUE TITLE
Search menu always visible

### ISSUE THREAD

**Issue by Radu-Fr** [mcguffin/acf-field-openstreetmap#35]
Hello @mcguffin ,
I hope this is the right place to post this, I'm new on GitHub.
First of all, congratulations for your great plugin!

I found a little issue in the plugin. If I use the search field to search an address, it will return you a list with the results. If I choose a result, a pin will be placed on the map, but the results list will not disappear. It will remain always visible. If you click on the search field again and press "Esc", the list will disappear, but on mobile you can't press "Esc" and the list will remain visible, above the map and you won't be able to see the map anymore.

Can you, please, help me with this issue?
Thanks!
Radu

**Comment by mcguffin** [comment]
Hi @Radu-Fr 
Thanks for the report. I think I was able to fix it. I'll release an update within the nex few days.
Regards, jörn

**Comment by Radu-Fr** [comment]
Hi @mcguffin,
Thank you very much!
Regards, Radu

**Comment by Radu-Fr** [comment]
Hi @mcguffin,
Thanks for your latest update of the plugin, but unfortunately this doesn't resolved the problem. It's still present in the updated version.
Have a great weekend!
Radu
