### ISSUE TITLE
Use MapTiler Cloud raster tile layers?

### ISSUE THREAD

**Issue by SRUC** [mcguffin/acf-field-openstreetmap#38]
Would it be possible to add support for MapTiler Cloud raster tile layers https://www.maptiler.com?

Thanks, David

**Comment by mcguffin** [comment]
Hi,
The plugin is including [Leaflet Providers extension](https://github.com/leaflet-extras/leaflet-providers) which contains all the providers for the plugin. (My time does not allow me to researching and maintain a provider list, so I added this as a dependecy.)
The most sustainable way would be to place your request there. (The developer seems to be very fond of pull request)

To get it fixed quickly for you, there is a filter named `acf_osm_leaflet_providers`, allowing you to add whatever map layer provider you desire.

Something like this should do it:
```php
add_filter('acf_osm_leaflet_providers', function( $providers ) {
    $providers['MapTiler'] = [
        'url' => 'https://{s}.tiles.some.domain.tld/map/{z}/{x}/{y}.png?access_key=abcd1234567890',
        'options' => [
            'attribution' => '&copy; The most generic map tile provider ever',
        ],
    ];
    return $providers;
});
```

All Provider definitions extracted from the Leaflet Providers extension. https://github.com/mcguffin/acf-openstreetmap-field/blob/master/etc/leaflet-providers.json (can be quite complex!)

**Comment by SRUC** [comment]
Thanks Jörn, that's really helpful - much appreciated.
