### ISSUE TITLE
Option to change markers format to french addresses format

### ISSUE THREAD

**Issue by vincin00b** [mcguffin/acf-field-openstreetmap#39]
Hello,

Is an option to change the markers output format possible ?
Now the format is like this : Rue de la Pomme 20, 31000 Toulouse, Occitanie France
But in France we put the number before the name of the street, like this: 20 rue de la Pomme, 31000 Toulouse, Occitanie France
![image](https://user-images.githubusercontent.com/19490661/70157227-81c0a880-16b5-11ea-838c-082f889e61ce.png)

So is there any option to change this in the field when you see your markers ?

Also is it possible to limit the possibilites of the search to only one country ?

Thank you for your time.

**Comment by mcguffin** [comment]
The OSM Plugin makes use of https://github.com/perliedman/leaflet-control-geocoder which makes calls to the [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) service (=the search engine of OpenStreetMap) to obtain the results. Nomitatim doesn't provide a country filter... – which hopefully answers your second question.

As for your other question: Luckily there is some logic in the leaflet control to apply custom address templates.  
I made the address templates localizable now, using placeholders for the different parts like city, street, house_no and so on, so if you craft a fr_FR locale in your WP, it should work. (Will be included in version 1.1.8)

**Comment by Cyrille37** [comment]
Hi, and thanks for sharing your really great work ;-) 

That could be at chapter "Features" in README file.
