### ISSUE TITLE
Geocoder create marker

### ISSUE THREAD

**Issue by cyril-flesch** [mcguffin/acf-field-openstreetmap#40]
Hello,

When we do a research with the geocoder and we click on an element from the result list for the moment it only center the map with the position of the place.

Is it possible when we click on a result to not only center on the position of the place but also create a marker and add it to the osm-markers list ?

Thank's

**Comment by mcguffin** [comment]
Well, this should be the exact functionality ... seems not working in your case. 
Do you see any JS errors in the developer console?

**Comment by cyril-flesch** [comment]
Yes, actually I was working with the version 1.1.5 and after an update to 1.1.8 it's now working.
