### ISSUE TITLE
no attribution

### ISSUE THREAD

**Issue by mjezegou** [mcguffin/acf-field-openstreetmap#42]
I would like not to have a link at the bottom of the map and so put attribution empty.
I am my own provider and I do not wish to display copyright.
As the only solution is to overload the leaflet-control-attribution leaflet-control class in display: none

<div class = "leaflet-control-attribution leaflet-control">
  <a href="https://leafletjs.com" title="A JS library for interactive maps"> Leaflet </a> 
</div>

**Comment by mcguffin** [comment]
All of these maps are copyrighted creative works of some kind. From a legal point of view, I think removing attribution is not an option.
From a moral point of view, all these services provide very beautiful maps for free to the public, so giving them credits is the least we can do to return the favor.
