### ISSUE TITLE
Missing dependencies: ACF Duplicate Repeater

### ISSUE THREAD

**Issue by ginsterbusch** [mcguffin/acf-field-openstreetmap#43]
Query Monitor complains about missing depencies, ie. ACF Duplicate Repeater. Out of some reason, the components are being loaded in the FRONTEND, instead of just in the admin interface.

And no, I'm not using the ACF Frontend Form option ..

Environment:
- ClassicPress 1.1.2 (essentially WP 4.9.13)
- no SSL / HTTPS
- ACF 5.8.7 Pro

Screenshot at: https://gfx.fwolf.de/image/KkTW

**Comment by ginsterbusch** [comment]
So is this a bug being abused as a feature (missing dependency, hence only loading properly when the required dep is available), or simply an oversight? The plugin description itself does not suggest the ACF Duplicate Repeater is an requirement to make this plugin work properly.

**Comment by mcguffin** [comment]
removed duplicate repeater support (plugin retired)
