### ISSUE TITLE
feature request: return parts of address in raw_data

### ISSUE THREAD

**Issue by dajocarter** [mcguffin/acf-field-openstreetmap#44]
It would be nice to have all of the parts of the address returned in raw_data.

Basically, this object
https://github.com/mcguffin/acf-openstreetmap-field/blob/a04ce41d688a4186dd8a6a5b5506d4ef21b13635/src/js/acf-input-osm.js#L581-L594

**Comment by vallica** [comment]
Hello,

I'm also looking for a way to get the city part of an stored address... is there a way to do this ? (in PHP of course)

Thanks in advance.

**Comment by scrobbleme** [comment]
Same here, thought this would already be possible.
