### ISSUE TITLE
Problem of <ul> result display

### ISSUE THREAD

**Issue by madvik** [mcguffin/acf-field-openstreetmap#48]
There is a display problem when suggesting address results :

![image](https://user-images.githubusercontent.com/3822529/81832736-238ad200-953f-11ea-99cd-1feab2341fdb.png)

**Comment by mcguffin** [comment]
Looks like the CSS is not properly loaded.
any errors in the browser developer console?

This is how it should look like:
<img width="847" alt="grafik" src="https://user-images.githubusercontent.com/402988/84589233-8b2d8900-ae2d-11ea-9c9d-2ea122eca8de.png">
