### ISSUE TITLE
Not working when ACF is included via theme

### ISSUE THREAD

**Issue by oasit** [mcguffin/acf-field-openstreetmap#5]
When ACF is loaded via the theme (between setup_theme and after_setup_theme) the OSM field is not available. No matter if loaded as plugin by WP or manually in the theme.

**Comment by mcguffin** [comment]
Hi,
does it work when you change line 22 in [include/ACFFieldOpenstreetmap/Core/Core.php](https://github.com/mcguffin/acf-field-openstreetmap/blob/master/include/ACFFieldOpenstreetmap/Core/Core.php#L22)
to 
```php
add_action( 'init' , array( $this , 'init_compat' ), 0 );
```
instead of `add_action('plugins_loaded', ...)`?

**Comment by oasit** [comment]
No, it doesn't.
'init' seems to be too late.
'plugins_loaded' seems to be toot early, ACF isn't loaded at plugins_loaded when ACF is loaded via the theme.

'acf/include_field_types' is working!

**Comment by mcguffin** [comment]
Okay, acf/include_field_types it is then...
Would you mind to run another test with the current master? If it works, I'll release it.

**Comment by oasit** [comment]
Sorry, because of some other small bugs and because we are using Mapbox for the frontend, we wrote an ACF Mapbox field on our own.
I can not and will not test the current master but I can confirm that 'acf/include_field_types' works with v0.1.8.
