### ISSUE TITLE
Stuck displaying the map in Elementor Pro

### ISSUE THREAD

**Issue by cybershellsolutions** [mcguffin/acf-field-openstreetmap#51]
I have tried multiple Elementor widgets to pull in the map dynamically but none appear to display on the frontend. I was hoping someone could help, I am clearly either doing something wrong or this is not what this plugin is meant to be used for. 

I have set up the field via the custom fields plugin:
-Field Name 
-Field Label 
-Field Type (OpenSteetMap)
-Return Format ( I have tried all) - currently set to iframe as I noticed others may be having problems with Leaflet JS. 

I have been able to include it via custom fields (as above) and I seem to have been able to include it in a frontend ACF form. 
It submits and saves in the post without issue however when I try to find a widget to display this in a page template for the post nothing is coming through?

Apologies for such a basic question but I am also not a Dev and don't code so I would be very grateful for any guidance.

Thanks.

**Comment by mcguffin** [comment]
Are Elementor Widgets just the same as WordPress widges? If so, the widget output needs to be coded seperately.
This might guide you in the right direction: https://www.advancedcustomfields.com/resources/get-values-widget/

Alernatively you can try a text widget, and render the Field value (the map) using a shortcode: https://www.advancedcustomfields.com/resources/shortcode/
