### ISSUE TITLE
Focus on marker

### ISSUE THREAD

**Issue by Messa1** [mcguffin/acf-field-openstreetmap#53]
Is there any settings i can set, that the map focus / center on the marker.
If customer only add address and don't change the map view (preview).
Map don't show the marker cause its out of the viewport of the map.

**Comment by dsturm** [comment]
Hej @Messa1, I think you could use the [`acf-osm-map-created` event](https://github.com/mcguffin/acf-openstreetmap-field/wiki/JS-Event:-Map-Created) with [`setView`](https://leafletjs.com/reference-1.6.0.html#map-setview) or [`fit-bounds`](https://leafletjs.com/reference-1.6.0.html#map-fitbounds).
