### ISSUE TITLE
Marker on exact position

### ISSUE THREAD

**Issue by wandersup** [mcguffin/acf-field-openstreetmap#55]
Hello
Whenever i add a marker which is not a specific address (a street)for example in a green field. The closest address is taken instead of the exact position of the marker.
Is it possible to save the exact GPS coordinates of a marker instead of address?

You can see an example in this video:
https://www.loom.com/share/59e8ada8bcf647deb08ce9dd570d85af
I have added 3 markers and all 3 use the same address.

**Comment by Cyrille37** [comment]
Hello,
I do not have this problem.
When you use the search engine, markers use nearest address.
But when you move them with the mouse, those new coordinates are stored. You can change the address label to write what you want.

**Comment by wandersup** [comment]
Oh Cool, you're right. Thanks for your help.
