### ISSUE TITLE
Many Warnings on installation => solution 

### ISSUE THREAD

**Issue by StudioDeTelevision** [mcguffin/acf-field-openstreetmap#56]
Use direct FileSystem method
Using direct method for handling filesystem tasks usually solves the problem.

Edit your wp-config.php file and add this code, if it doesn’t already exist:

PHP
define('FS_METHOD', 'direct');

**Comment by mcguffin** [comment]
Should probably be gone with 8590acdd1a293809b2494aaeeb8b4e1b49b04493. 
(I saw lots of warnings too, when investigating #61)
