### ISSUE TITLE
Some translations gets wrongly escaped

### ISSUE THREAD

**Issue by jooola** [mcguffin/acf-field-openstreetmap#59]
Hello !
I have french translations on my WP site, and the `Search...` placeholder get translated into :
![image](https://user-images.githubusercontent.com/19195485/101282292-a4a80000-37d4-11eb-8fb8-d0c71f49d841.png)

I'm not sure where the translation comes from, but something is odd here or in the translations files. Maybe this should not be escaped on this side ? 

Thanks for this tool !

**Comment by mcguffin** [comment]
Salu,
the French Translation comes from [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/acf-openstreetmap-field/stable/fr/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=current&page=1), where [btpub](https://profiles.wordpress.org/btpub/) thankfully translated my plugin.

As you can see, he didn't use the unicode char `…` like in the original but the corresponding HTML entity `&hellip;`. IMHO that's something he should fix.

Escaping strings is always a good thing for security. PO files can be misused an attack vector for code injection.
