### ISSUE TITLE
Mixed Content warnings

### ISSUE THREAD

**Issue by djcowan** [mcguffin/acf-field-openstreetmap#6]
Simply raising the issue for tracking here. Love the plugin – hoping ACF implements this as an alternative map field

Issue:
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.
"page" was loaded over HTTPS, but requested an insecure image 'http://b.tiles.wmflabs.org/bw-mapnik/9/464/"image".png'. This content should also be served over HTTPS.

Related articles:
https://help.openstreetmap.org/questions/63360/httpbtileosmorg-for-https
https://github.com/Leaflet/Leaflet/issues/3186

**Comment by mcguffin** [comment]
https://b.tiles.wmflabs.org/bw-mapnik/9/464/123.png results in a certificate error.  
However https://tiles.wmflabs.org/bw-mapnik/9/464/123.png works. Applied a quick'n'dirty patch, substituting the original URLs from leaflet providers.
Related: https://github.com/leaflet-extras/leaflet-providers/pull/311
