### ISSUE TITLE
Providers are not loaded properly in the admin

### ISSUE THREAD

**Issue by Ale-** [mcguffin/acf-field-openstreetmap#61]
The map is blank in the field widget in the admin. The problem seems to be related to a null provider value. It seems the problem is related to this block in Leaflet Provider:

```
if ( is_null( $this->leaflet_providers ) ) { 
     $this->leaflet_providers = json_decode( $core->read_file( 'etc/leaflet-providers.json' ), true );    
}
```
That is related to this condition in Plugin.php:

`if ( ! WP_Filesystem() ) return false;`

As WP_Filesystem is false, provider is not being read properly so the map is blank.

My quick&dirty workaround right now is to hardcode the provider I'm using in the JS code, replacing it through functions.php. 

This happens on a Wordpress 5.6 served by PHP 7.4.3

**Comment by Ale-** [comment]
After studying a bit more it seems a problem of permissions. It seems that www-data has to be the owner of all the wordpress tree to WP_Filesystem to return something else than false.

**Comment by mcguffin** [comment]
Thanks for bringing this to my attention!
I wasn't aware, that `WP_Filesystem()` always checks for writeability, which is not needed in that case.
I'll fix this in the upcoming release!
