### ISSUE TITLE
Problems with umlauts

### ISSUE THREAD

**Issue by sebastian-works** [mcguffin/acf-field-openstreetmap#63]
Hello!
Thanks for creating this plugin! I have found an issues with umlauts. 
When I try to enter e.g Österreich as the country-name it creates: "u00d6sterreich" after saving. Same happens to the street name etc. 
Is there a way to solve this issue to use umlauts probably?

Thanks!

**Comment by mcguffin** [comment]
Hi @albertvisuals,
I can't reproduce this so far ... 
Which Browser and which localization are you using?
Does it still appear in a different Browser?
Can you post an URL, where I can see the issue?
Thanks!

**Comment by sebastian-works** [comment]
Hello! 
Sorry have somehow missed the email. 
I have checked in Safari and Firefox. 

I am using the de-AT (German Austria) localization. 
The site is locked because of a testing environment, so I can't share access publicly, but I could share a private link. 

Thanks!
