### ISSUE TITLE
BUG: Tooltips of markers don't open in Safari

### ISSUE THREAD

**Issue by Leo24790** [mcguffin/acf-field-openstreetmap#65]
Tooltips don't open when clicking on markers.
I'm using Safari 14.0.2 for Mac and on iPhone with iOS 14.3.

On the iPhone it looks like something is happening but the marker isn't fully showing up.

Chrome 87 an Firefox 72 work without problems.

**Comment by mcguffin** [comment]
Hi @Leo24790,
thanks for the report!
This issue is already known to leaflet: https://github.com/Leaflet/Leaflet/issues/7255
But it should be fixable in the plugin too.

I'll come up with new release a little later today.

**Comment by Leo24790** [comment]
Great. Works perfectly fine in Safari now. Thank you
