### ISSUE TITLE
Print only the address

### ISSUE THREAD

**Issue by sebastian-works** [mcguffin/acf-field-openstreetmap#69]
Hello!

I have a short question. Is it possible to just print the address, without the map if the return value is set to Leaflet JS?

Thanks!

**Comment by mcguffin** [comment]
If the return value is set to Leaflet JS it will print a leaflet map.  
You may like to have a look at the  [Theme Overrides](https://github.com/mcguffin/acf-openstreetmap-field/wiki/Theme-Overrides) feature.
