### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ffoodd** [mcguffin/acf-field-openstreetmap#7]
Hi there, 

thanks for this plugin, extremely useful!

Could you please release your last changes?
As of 0.1.8, maps don't load correctly inmy projects; applying the current state of master branch fixes it.

I guess this has something to do with updating Leaflet and providers.

Thanks again, have a nice day!

**Comment by mcguffin** [comment]
0.1.10 is out!

**Comment by ffoodd** [comment]
Wow thanks a lot for being so reactive!
