### ISSUE TITLE
How to change the returned raw data language? 

### ISSUE THREAD

**Issue by solakisk** [mcguffin/acf-field-openstreetmap#72]
When I enter an address to the map, the language of the data is not English, but they are returned to me in my country's language, as it seems. Is there any way that can change the language of the returned data?

**Comment by mcguffin** [comment]
I'm afraid, there's none.  
Geocoding is handled by [nominatim](https://nominatim.org/release-docs/latest/api/Overview/) which is not translated.
Issue #71 is dealing with alternatives to nominatim.
