### ISSUE TITLE
Validation fail. 'Open Street value is required'

### ISSUE THREAD

**Issue by anthonyomalley** [mcguffin/acf-field-openstreetmap#8]
If the openstreetmap field is set to required,  I see 'Validation failed. 1 field requires attention' when attempting to publish despite the field being completed (a marker placed and an address inserted in the input beneath the map).

Also, if the openstreetmap field is set as conditional and hidden until another field is completed, only the top left corner of the map renders correctly, the rest remains grey.

**Comment by mortennh** [comment]
Still getting the error described by OP

EDIT: 

The code you have  added is always true. Maybe checking if markers are set but `$value` is an object as a sanitized string...

```php
if ( empty($value) || empty($value['lat']) || empty($value['lng'] ) ) {
    return false;
}
```
