### ISSUE TITLE
Mapbox is not displaying custom styles

### ISSUE THREAD

**Issue by thohug** [mcguffin/acf-field-openstreetmap#82]
When adding a Mapbox-Base-Map it's just using the standard mapbox-map. It would be nice if custom styles would be supported (probably Style-URL needs to be added apart from Access Token).

**Comment by interpixels** [comment]
Indeed, it would be fantastic if custom Mapbox styles were supported.

**Comment by mcguffin** [comment]
Just added a Wiki-Page on how to add a custom mapbox style:
https://github.com/mcguffin/acf-openstreetmap-field/wiki/Custom-Mapbox
