### ISSUE TITLE
Contact [[User: TheDJ]] if you want to maintain OSMdb and/or the wmflabs' OSM tiles server.

### ISSUE THREAD

**Issue by ncamaa** [mcguffin/acf-field-openstreetmap#83]
Does anyone else get that?
![image](https://user-images.githubusercontent.com/25122974/165030586-f326998c-8f82-4017-b560-1fd22ed6f8d0.png)

**Comment by mcguffin** [comment]
Jep.
Looks like the Wikimedia Foundation is not willing to offer map services any more...
