### ISSUE TITLE
Is it possible to insert the searchable map of the backend in a front end user edit profile page?

### ISSUE THREAD

**Issue by ghost** [mcguffin/acf-field-openstreetmap#90]
Hello, first of all sorry if this was not supposed to be published here... I don't know where to post it.
I've been trying to insert the searchable map of the backend in a front end user edit profile page with some customization but I haven't found a solution for this.... is that possible with your plugin at this moment? Thanks in advance.

**Comment by mcguffin** [comment]
Hello and welcome to your very first issue!
If you are into coding you might have some luck creating an [ACF Frontend Form](https://www.advancedcustomfields.com/resources/create-a-front-end-form/) and passing `'post_id' => 'user_'.get_current_user_id()` to `acf_form()`.   
If you want to set things up brom the backend – no coding – [Frontend Admin for ACF](https://de.wordpress.org/plugins/acf-frontend-form-element/) might be helpful.

**Comment by ghost** [comment]
Thanks a lot, it worked!
