### ISSUE TITLE
Add-on gives center coordinates instead of marker coordinates

### ISSUE THREAD

**Issue by mrsalto** [mcguffin/acf-field-openstreetmap#95]
Hello,

I wanted to use this addon, so that client could add marker on front-end and in notification the admin would get the coordinates. What I noticed is that marker coordinates are not given for admin, instead the map center coordinated which was set in plugin field settings (acf) is given for admin. Can You fix this please? Or simply I need just to add some settings to make it work?

**Comment by mcguffin** [comment]
Map center is stored independently from marker position(s). 
Please refer to this [Wiki page](https://github.com/mcguffin/acf-openstreetmap-field/wiki/Usage#raw-data-structure).
I surely will not change this behaviour – some people (including myself) have build other stuff on top of it.

**Comment by mrsalto** [comment]
Ok, no worries bout that. I just wonder how to get that marker coordinates in ACF? Basically, I ACF as work form, so nothing is posted on website, only email received. Right now it does not matter where I put the marker, in email notification I receive map center coordinates. Can You kindly please let me know how to solve this one in my case?

For example now I select RAW Data and the output to notification email is:
"53.55064, 10.00065, 12, , , OpenStreetMap.Mapnik, 53.55064, 10.00065"

While 53.55064, 10.00065 is map center coordinates, not marker coordinates.

Hope You can help. Thanks
