### ISSUE TITLE
Storage of the geocoding information not consistent

### ISSUE THREAD

**Issue by lizuka** [mcguffin/acf-field-openstreetmap#96]
I need to use the postcode information stored in the raw data (part of the rest of the geocode information).
But I've noticed that I don't have it for all the posts I've created.

When I'm using the geocoding tool in the field admin panel :
1. I search for an address, the marker appears at the correct location on the map.
2. I save my new post
3. I check in the postmeta table, but the geocode entry is empty.  I do have lat/lng and label for each marker

However if I move the marker or create one by double-clicking on the map, the geocode information is stored after the content is saved.

Am I missing something?

**Comment by fahrenheit451fra** [comment]
Hello,
I have exactly the same problem. Did you solve it?

thx

**Comment by VolodymyrMuzyka** [comment]
Hi! Same here.

**Comment by lizuka** [comment]
Hi, 
I'm afraid not. The final editor has to fill another ACF field for the post code.

**Comment by Cyrille37** [comment]
Hi. I'm investigating but haven't found the solution yet ...

In _map-input.js_ on event _markgeocode_ we seen that geocode data are not set
```js
const latlng =  e.geocode.center,
	label = this.parseGeocodeResult( [ e.geocode ], latlng ),
	marker_data = {
		label: label,
		default_label: label,
		lat: latlng.lat,
		lng: latlng.lng,
		geocode: [],
	}
```
but a few lines later we see it fire event `osm-editor/marker-geocode-result`
```js
this.el.dispatchEvent( new CustomEvent( 'osm-editor/marker-geocode-result', {
 detail: { 
  model,
  geocode: e.geocode,
  previousGeocode
 }
} ), { bubbles: true } )
```

To listening on `osm-editor/marker-geocode-result` event we must set `useCapture=true`.
```javascript
window.addEventListener( 'osm-editor/marker-geocode-result',
 e => { console.debug('osm-editor/marker-geocode-result', e.detail ); },
 true
);
```

The javascript side of ACF field is listening to `osm-editor/marker-geocode-result` and call : 
```javascript
geocodeResult: function( e ) {
	const { model, geocode, previousGeocode } = e.detail
	acf.doAction('acf-osm/marker-geocode-result', model, this, geocode, previousGeocode );
},
```
but there is not a matching `acf.addAction('acf-osm/marker-geocode-result'...)` I deduce that some code processes the `Backbone.model` to fill the acf field value ...
 
## The solution :wink: 

To get the full geocoding result at php side we need to add a  piece of Javascript  :
```javascript
acf.addAction('acf-osm/marker-geocode-result', function( markerModel, osm, geocodeResult, prevGeocodeResult ) {
	console.debug('action "osm-editor/marker-geocode-result"', markerModel, osm, geocodeResult);
	markerModel.set('geocode', geocodeResult.properties.address );
});
```

Now all that remains is to find how to add this javascript when an osm-acf-field is presents for input ...
