### ISSUE TITLE
Provide accept-language

### ISSUE THREAD

**Issue by 1ucay** [mcguffin/acf-field-openstreetmap#97]
Hello, can you please add accept-language parameter to ACF settings for Nominatim geocode?
https://help.openstreetmap.org/questions/38202/is-it-possible-to-specify-a-language-for-results-in-reverse-geocoding
Like this, it can be overide via filter - for developer it would be useful. For example we can overide this settings over get_user_locale()

Thank you
.

**Comment by 1ucay** [comment]
Sorry, better would be get_locale(), because we need uniform address street across website.

**Comment by 1ucay** [comment]
in acf-osm-frontend.js line #16057

      var params = geocodingParams(this.options, {
        q: query,
        limit: 5,
	    'accept-language': window.wp.editor.getDefaultSettings().tinymce.language,
        format: 'json',
        addressdetails: 1
      });

**Comment by mcguffin** [comment]
1.5.0 introduces a WordPress filter, that should solve your problem.
@see https://github.com/mcguffin/acf-openstreetmap-field/wiki/WordPress-Filters#acf_osm_nominatim_options

**Comment by 1ucay** [comment]
Thank you!

**Comment by 1ucay** [comment]
Hello, i just tried in new project and not working. It seems that parameters are not set.
https://nominatim.openstreetmap.org/search?q=Warsaw&limit=5&format=json&addressdetails=1
