### ISSUE TITLE
About Plugin Support and Updates

### ISSUE THREAD

**Issue by EstebanToloza** [mcguffin/acf-field-openstreetmap#98]
Hey there! Wow, you've done an awesome job with this plugin, thank you so much! I was wondering if this plugin is still being actively maintained or if it has been abandoned. I'm considering using it for a project and I just want to make sure that the plugin is regularly updated. Your confirmation would be greatly appreciated!

By the way, I apologize if this isn't the appropriate place to inquire, but I wasn't sure where else I could ask about it. Thanks for understanding!

**Comment by mcguffin** [comment]
@EstebanToloza If my schedule allows, I'm still maintaining the plugin.
As a non-profit project it may take a while to the next update…
